//
// Created by de56008 on 16.11.2023.
//

#ifndef PROZEDURALE_PROGRAMMIERUNG_HUFFMAN_COMMON_H
#define PROZEDURALE_PROGRAMMIERUNG_HUFFMAN_COMMON_H

#endif //PROZEDURALE_PROGRAMMIERUNG_HUFFMAN_COMMON_H
